### ISSUE TITLE
Call Stack Exceeded when calling the destroy method

### ISSUE THREAD

**Issue by derekzernach** [snamoah/dynogels-promise#1]
When calling the destroy method it seems to end up in a recursive loop it can’t get out of in the table.js file at this location and ends up throwing a call stack exceeded and crashes…

![image](https://user-images.githubusercontent.com/12968609/60124760-f4654980-974f-11e9-9d5e-01ce57e175cb.png)

**Comment by snamoah** [comment]
@derekzernach will take a look at it, thanks

**Comment by snamoah** [comment]
@derekzernach found the issue.. published version [1.0.18](https://www.npmjs.com/package/dynogels-promise) which contains the fix
